import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import { defineConfig } from 'vite';
import { configDefaults } from 'vitest/config';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';

// Single-source the app version from package.json (read here so it never enters the TS
// program as a JSON import) and expose it via `define` — spec §2.3.7.
const pkg = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8')) as {
  version: string;
};

/**
 * Cross-origin isolation headers — spec §2.3.1. SharedArrayBuffer and the SQLite OPFS
 * VFS require a cross-origin-isolated context; the canonical execution environment is
 * `npm run dev` / `npm run preview`, so both servers set the headers directly (locked
 * decision §1.3 #14). On a static host that cannot send headers — GitHub Pages — the
 * service worker injects the same three headers instead (src/sw.ts).
 */
const crossOriginIsolationHeaders = {
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Embedder-Policy': 'require-corp',
} as const;

/**
 * Public base path. Defaults to '/' so the canonical local-first environment (§1.3 #14)
 * is unchanged: `npm run dev`, `npm run preview`, Run.ps1 and the browser smoke all keep
 * serving from the root. The Pages deploy workflow sets BANGERBOX_BASE=/BangerBox/ for
 * its build only — a project Pages site is served from a repository subpath, and the
 * manifest `id`/`scope`/`start_url` must track it or the PWA will not install.
 */
const BASE = process.env.BANGERBOX_BASE ?? '/';

// Dark theme colour for the manifest/splash — mirrors the `--color-bb-bg` design token
// in src/styles/index.css (spec §2.4: manifest colours match the design tokens).
const THEME_COLOUR = '#141317';

// https://vite.dev/config/
export default defineConfig({
  base: BASE,

  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },

  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      // spec §2.3.5 — injectManifest with a single custom worker (src/sw.ts).
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      // `prompt` (not `autoUpdate`): a new build installs but stays waiting until the
      // user accepts the "Reload to update" toast — never reload out from under an
      // unsaved project (spec §2.4).
      registerType: 'prompt',
      // Registration happens in app code via `virtual:pwa-register` (usePwaUpdate).
      injectRegister: null,
      injectManifest: {
        // Precache glob includes `wasm`; SQLite + DSP wasm binaries need the raised
        // 16 MiB single-file cap (spec §2.3.5).
        globPatterns: ['**/*.{js,css,html,wasm,woff2,svg,ico,png}'],
        maximumFileSizeToCacheInBytes: 16 * 1024 * 1024,
      },
      manifest: {
        // spec §2.4 — id/scope/start_url track the base path (see BASE above); landscape
        // tablet form factor; en-GB.
        id: BASE,
        scope: BASE,
        start_url: BASE,
        name: 'BangerBox',
        short_name: 'BangerBox',
        description: 'BangerBox — an offline-first, browser-based DAW, sequencer, and sampler.',
        lang: 'en-GB',
        display: 'standalone',
        orientation: 'landscape',
        theme_color: THEME_COLOUR,
        background_color: THEME_COLOUR,
        // SVG master icon + raster fallbacks; the maskable PNG is a separate asset with
        // safe-zone padding — never the `any` icon reused (spec §2.4). Generated by
        // scripts/generate-icons.mjs.
        icons: [
          { src: 'icons/bangerbox.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
          { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: 'icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      // Dev relies on the dev-server COOP/COEP headers, not the SW — spec §2.3.5.
      devOptions: { enabled: false },
    }),
  ],

  resolve: {
    // spec §2.3.6
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },

  // @sqlite.org/sqlite-wasm ships its own worker + wasm asset and must not be
  // pre-bundled by esbuild — spec §2.3.3 (official package guidance).
  optimizeDeps: {
    exclude: ['@sqlite.org/sqlite-wasm'],
  },

  // spec §2.3.2
  worker: {
    format: 'es',
  },

  server: {
    headers: { ...crossOriginIsolationHeaders },
  },
  preview: {
    headers: { ...crossOriginIsolationHeaders },
  },

  test: {
    environment: 'happy-dom',
    globals: true,
    setupFiles: ['./src/test/setup.ts'],
    // Build the gitignored DSP kernel .wasm artefacts once, in the main process, before any
    // worker starts — building them lazily from the test helper had every kernel test file
    // racing to spawn its own `asc` run over the same output paths.
    globalSetup: ['./src/test/buildKernels.ts'],
    css: false,
    // worker_threads pool: on Node 25 the default forks pool hits a cold-start spawn
    // race that fails whole runs.
    pool: 'threads',
    // spec §2.3.9 — concurrent-agent worktrees carry full copies of src/ and their own
    // node_modules; sweeping them loads a second React and breaks hooks for every test.
    exclude: [...configDefaults.exclude, '**/.claude/worktrees/**'],
  },
});
